name: Build

on:
  push:
    branches: [ "stable", "dev", "dev-feature" ]
  pull_request:
    branches: [ "stable", "dev", "dev-feature" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
